execute:
    error: true # Allow errors
    echo: true
    enabled: true
    daemon: 300
julia:
    exeflags: ["--project=@.", "--threads=1"]
    author: 
        - "Aapeli Vuorinen"
        - "Yoni Nazarathy"
format:
  html:
    include-in-header:
        text: |
              <div style="max-width: 1368px; margin: 0 auto;padding:20px">
                <h1>A Crash Course on the Julia Language and Ecosystem</h1>
                <p>An <a href="https://www.accumulationpoint.com/">Accumulation Point</a> workshop for 
                    <a href="https://www.aims.gov.au/">AIMS</a>, delivered during June, 2025.
                  See workshop materials in the AIMS <a href="https://github.com/open-AIMS/Julia_ML_training">GitHub repo</a>.
                </p>
              </div>
    include-before-body:
        text: |
            <center>
                <p>
                    <a href="../index.html" style="display: inline-block; padding: 5px 10px">Welcome</a> 
                    |
                    <a href="../unit1/unit_1.html" style="display: inline-block; padding: 5px 10px">Unit 1</a> 
                    |
                    <a href="../unit2/unit_2.html" style="display: inline-block; padding: 5px 10px">Unit 2</a> 
                    |
                    <a href="../unit3/unit_3.html" style="display: inline-block; padding: 5px 10px">Unit 3</a> 
                    |
                    <a href="../unit4/unit_4.html" style="display: inline-block; padding: 5px 10px">Unit 4</a> 
                    |
                    <a href="../unit5/unit_5.html" style="display: inline-block; padding: 5px 10px">Unit 5</a> 
                </p>
            </center>
    include-after-body:
        text: |
            <center>
                <p>
                    <a href="../index.html" style="display: inline-block; padding: 5px 10px">Welcome</a> 
                    |
                    <a href="../unit1/unit_1.html" style="display: inline-block; padding: 5px 10px">Unit 1</a> 
                    |
                    <a href="../unit2/unit_2.html" style="display: inline-block; padding: 5px 10px">Unit 2</a> 
                    |
                    <a href="../unit3/unit_3.html" style="display: inline-block; padding: 5px 10px">Unit 3</a> 
                    |
                    <a href="../unit4/unit_4.html" style="display: inline-block; padding: 5px 10px">Unit 4</a> 
                    |
                    <a href="../unit5/unit_5.html" style="display: inline-block; padding: 5px 10px">Unit 5</a> 
                </p>
                <br><br><br><br><br>
            </center>
    self-contained-math: true
    anchor-sections: true
    theme: default
    respect-user-color-scheme: true
    toc: true
    toc-depth: 1
    toc-expand: 2
    toc-location: left
    toc-title: Contents
    number-sections: true
    number-depth: 3
    code-summary: Show/Hide Code
    code-tools:
        caption: Download unit source
        source: true
bibliography: ../references.bib
fig-format: svg
fig-width: 8
fig-height: 6
