name: Generate course material archive and Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      commit_sha: ${{ github.sha }}
    steps:
      - name: Set up Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: '1'
          arch: 'default'
          show-versioninfo: 'false'
          project: '.'

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.7.28

      - name: Checkout code for build
        uses: actions/checkout@v4

      - name: Build units
        run: |
          julia --project=. -e 'using Pkg; Pkg.activate("."); Pkg.instantiate()'
          make ci

      - name: Archive artifacts for release job
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: |
            index.html
            index_files/**/*
            unit*/unit_*.html
            unit*/unit_*_files/**/*

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: ./_site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
