name: Generate and deploy course material

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      commit_sha: ${{ github.sha }}
    steps:
      - uses: julia-actions/setup-julia@v2
        with:
          version: '1'
          arch: 'default'
          show-versioninfo: 'false'
          project: '.'
      - uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.7.28
      - uses: actions/checkout@v4
      - run: make ci
      - run: pwd
      - run: ls -lah
      - uses: actions/upload-pages-artifact@v3
        with:
          path: |
            index.html

  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
